server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lenyn15/Isabel-project.git
          searchPaths: config-server
        default-label: main
  security:
    user:
      name: root
      password: s3cr3t